(function(){'use strict';var M=window.TrainingMath,U=window.TrainingUI;
function shrink(root){var l1=.6,l2=.5,z=.4,controls=U.el('div','opt-controls',null,root);U.range(controls,'L1 strength λ₁',0,2,.1,l1,function(v){l1=v;draw();});U.range(controls,'L2 strength λ₂',0,2,.1,l2,function(v){l2=v;draw();});U.range(controls,'Unregularized coordinate z',-3,3,.1,z,function(v){z=v;draw();});var chart=U.svg(root,'Exact regularized coordinate versus unregularized coordinate'),stats=U.el('div','opt-readout',null,root),out=U.status(root);
function draw(){var points=[];for(var x=-3;x<=3.001;x+=.03)points.push(x);U.plot(chart,[{name:'L1 · soft threshold',color:'#137b68',points:points.map(function(x){return [x,M.soft(x,l1)];})},{name:'L2 · smooth shrinkage',color:'#477fa2',points:points.map(function(x){return [x,x/(1+l2)];})},{name:'Elastic net',color:'#b66929',points:points.map(function(x){return [x,M.elastic(x,l1,l2)];})}],{xmin:-3,xmax:3,ymin:-3,ymax:3,xlabel:'Unregularized optimum z',ylabel:'Regularized optimum w*'});var a=M.soft(z,l1),b=z/(1+l2),c=M.elastic(z,l1,l2);U.read(stats,[['L1 optimum',U.fmt(a)],['L2 optimum',U.fmt(b)],['Elastic-net optimum',U.fmt(c)],['Elastic-net objective',U.fmt(.5*(c-z)*(c-z)+l1*Math.abs(c)+.5*l2*c*c)]]);out.textContent='Exact minimizers of ½(w − z)² plus the stated penalty. The zero region is |z| ≤ λ₁. No neural network is trained in this coordinate experiment.';root.dataset.result=JSON.stringify([a,b,c]);}draw();}
function decay(root){var lambda=.2,p=.1,c=U.el('div','opt-controls',null,root);U.range(c,'Decay strength λ',0,1,.05,lambda,function(v){lambda=v;draw();});U.range(c,'Second preconditioner entry',.05,2,.05,p,function(v){p=v;draw();});var chart=U.svg(root,'Coordinate two under coupled L2 and decoupled decay'),stats=U.el('div','opt-readout',null,root);function draw(){var a=M.decayPath(lambda,p,40);U.plot(chart,[{name:'L2 through P: w₂',color:'#137b68',points:a.map(function(q){return [q[0],q[1]];})},{name:'Direct decay: w₂',color:'#b66929',points:a.map(function(q){return [q[0],q[2]];})}],{xmin:0,xmax:40,ymin:0,ymax:2,xlabel:'Update number',ylabel:'Weight value'});U.read(stats,[['Coupled w₂ after 1 step',U.fmt(a[1][1])],['Direct w₂ after 1 step',U.fmt(a[1][2])],['Both methods: w₁ at step 40',U.fmt(a[40][2])]]);root.dataset.result=JSON.stringify(a[40]);}draw();}
function dropout(root){var p=.5,mode='activation',seed=19,c=U.el('div','opt-controls',null,root);U.range(c,'Drop probability p',0,.8,.05,p,function(v){p=v;draw();});U.select(c,'Mask type',[['activation','Activation dropout'],['connection','Independent DropConnect']],mode,function(v){mode=v;draw();});U.button(c,'Resample masks',function(){seed++;draw();});var chart=U.svg(root,'Running output means across sampled dropout masks'),stats=U.el('div','opt-readout',null,root),out=U.status(root);function draw(){var a=M.dropoutSamples(p,mode,seed,1000),s=[0,0],pts=[[],[]];a.forEach(function(row,i){row.y.forEach(function(y,j){s[j]+=y;if(i===0||i%10===9)pts[j].push([i+1,s[j]/(i+1)]);});});var means=s.map(function(x){return x/1000;}),cov=M.mean(a.map(function(row){return (row.y[0]-means[0])*(row.y[1]-means[1]);})),ys=pts[0].concat(pts[1]).map(function(x){return x[1];});U.plot(chart,[{name:'Mean output 1',color:'#137b68',points:pts[0]},{name:'Mean output 2',color:'#477fa2',points:pts[1]},{name:'Expected output 1',color:'#b66929',points:[[1,3.5],[1000,3.5]]}],{xmin:1,xmax:1000,ymin:Math.min(0,Math.min.apply(null,ys)),ymax:Math.max(4,Math.max.apply(null,ys)),xlabel:'Number of mask draws',ylabel:'Running mean'});U.read(stats,[['Expected means','3.5 and 1'],['Sampled means',means.map(U.fmt).join(', ')],['Expected covariance',U.fmt(mode==='activation'?1.25*p/(1-p):0)],['Sampled covariance',U.fmt(cov)]]);out.textContent='First draw: masks ['+a[0].mask[0].join(', ')+'] and ['+a[0].mask[1].join(', ')+']; outputs '+a[0].y.map(U.fmt).join(', ')+'. 1 = keep; surviving contributions are divided by '+U.fmt(1-p)+'.';root.dataset.result=JSON.stringify([means,cov]);}draw();}
document.querySelectorAll('[data-demo="dropout"]').forEach(dropout);
document.querySelectorAll('[data-demo="decay"]').forEach(decay);
document.querySelectorAll('[data-demo="shrink"]').forEach(shrink);
})();
