(function(root){'use strict';var M={};
M.soft=function(z,t){return Math.sign(z)*Math.max(Math.abs(z)-t,0);};
M.elastic=function(z,l1,l2){return M.soft(z,l1)/(1+l2);};
M.rng=function(seed){var s=seed>>>0;return function(){s=(Math.imul(s,1664525)+1013904223)>>>0;return (s+.5)/4294967296;};};
M.normal=function(r){return Math.sqrt(-2*Math.log(r()))*Math.cos(2*Math.PI*r());};
M.mean=function(a){return a.reduce(function(s,x){return s+x;},0)/a.length;};
M.variance=function(a){var m=M.mean(a);return M.mean(a.map(function(x){return (x-m)*(x-m);}));};
M.projectBall=function(z,c){var n=Math.hypot.apply(null,z),a=n>c?c/n:1;return z.map(function(x){return a*x;});};
M.decayPath=function(lambda,p,steps){var a=2,b=2,out=[[0,a,b]];for(var i=1;i<=steps;i++){a*=1-.1*lambda*p;b*=1-.1*lambda;out.push([i,a,b]);}return out;};
M.dropoutSamples=function(p,mode,seed,n){var r=M.rng(seed),q=1-p,terms=[[1,1,.5,1],[.5,2,-.5,-1]],out=[];for(var k=0;k<n;k++){var shared=terms[0].map(function(){return r()<q?1:0;}),masks=terms.map(function(){return mode==='activation'?shared:shared.map(function(){return r()<q?1:0;});});out.push({mask:masks,y:terms.map(function(row,i){return row.reduce(function(sum,x,j){return sum+x*masks[i][j]/q;},0);})});}return out;};
M.structuredMask=function(mode,p,seed){var r=M.rng(seed),branch=r()>=p?1:0,b=Math.round(8*Math.sqrt(p));return [0,1].map(function(){var channel=r()>=p?1:0,x=Math.floor(r()*(9-b)),y=Math.floor(r()*(9-b));return Array.from({length:64},function(_,i){return mode==='element'?(r()>=p?1:0):mode==='channel'?channel:mode==='branch'?branch:((i%8>=x&&i%8<x+b&&Math.floor(i/8)>=y&&Math.floor(i/8)<y+b)?0:1);});});};
M.cutmix=function(lambda,cx,cy){var b=Math.round(8*Math.sqrt(1-lambda)),left=Math.floor(cx-b/2),top=Math.floor(cy-b/2),x0=Math.max(0,left),x1=Math.min(8,left+b),y0=Math.max(0,top),y1=Math.min(8,top+b);return {x0:x0,x1:x1,y0:y0,y1:y1,side:b,lambda:1-Math.max(0,x1-x0)*Math.max(0,y1-y0)/64};};
root.TrainingMath=M;})(typeof window==='undefined'?globalThis:window);
