#!/usr/bin/env python3
"""Splice the LeetCode-contests subtree into blog.js (BLOG_TREE) and
bulk-append BLOG_POSTS entries into blog-posts.js.

Idempotent: looks for marker comments and replaces the block in place.

  blog.js:        // LCBLOG-START ... // LCBLOG-END   (inside dsa.children)
  blog-posts.js:  /* LCBLOG-START */ ... /* LCBLOG-END */  (inside BLOG_POSTS)
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
MANIFEST = REPO / "tools" / "contests.json"
BLOG_JS = REPO / "blog.js"
POSTS_JS = REPO / "blog-posts.js"


# ---------- BLOG_TREE block ----------

def js_str(s: str) -> str:
    return "'" + s.replace("\\", "\\\\").replace("'", "\\'") + "'"


def build_tree_block(contests: list[dict]) -> str:
    """Return the JS source for the leetcode-contests subtree (10-space indent
    matches the existing dsa-children indentation)."""
    pad = " " * 6  # depth inside dsa.children (siblings of `trees`)
    out: list[str] = []
    out.append(pad + "// LCBLOG-START (auto-generated by tools/update_registries.py — do not edit by hand)")
    out.append(pad + "{")
    out.append(pad + "  name: 'leetcode-contests',")
    out.append(pad + "  label: 'LeetCode Past Contests',")
    out.append(pad + "  children: [")

    for kind, label in (("weekly", "Weekly Contests"), ("biweekly", "Biweekly Contests")):
        bucket = [c for c in contests if c["kind"] == kind]
        bucket.sort(key=lambda c: c["number"])
        out.append(pad + "    {")
        out.append(pad + f"      name: {js_str(kind)},")
        out.append(pad + f"      label: {js_str(label)},")
        out.append(pad + "      children: [")
        for ci, c in enumerate(bucket):
            num3 = f"{c['number']:03d}"
            human = f"{kind.capitalize()} {c['number']}"
            base = f"dsa/leetcode-contests/{kind}/{num3}"
            problems = c["problems"]
            out.append(pad + "        {")
            out.append(pad + f"          name: {js_str(num3)},")
            out.append(pad + f"          label: {js_str(human)},")
            out.append(pad + "          children: [")
            files = [f"{base}/index.html"] + [
                f"{base}/q{p['order']}-{p['slug']}.html" for p in problems
            ]
            titles = [human + " · Overview"] + [
                f"Q{p['order']}. {p['title']}" for p in problems
            ]
            for i, (f, t) in enumerate(zip(files, titles)):
                links = []
                if i > 0:
                    links.append(files[i - 1])
                if i < len(files) - 1:
                    links.append(files[i + 1])
                links_js = "[" + ", ".join(js_str(l) for l in links) + "]"
                comma = "," if i < len(files) - 1 else ""
                out.append(
                    pad
                    + f"            {{ title: {js_str(t)}, file: {js_str(f)}, links: {links_js} }}{comma}"
                )
            comma = "," if ci < len(bucket) - 1 else ""
            out.append(pad + "          ]")
            out.append(pad + "        }" + comma)
        out.append(pad + "      ]")
        comma = "," if kind == "weekly" else ""
        out.append(pad + "    }" + comma)

    out.append(pad + "  ]")
    out.append(pad + "}")
    out.append(pad + "// LCBLOG-END")
    return "\n".join(out)


def splice_blog_js(contests: list[dict]) -> None:
    src = BLOG_JS.read_text(encoding="utf-8")
    # Strip any existing block.
    pattern = re.compile(r"^[ \t]*// LCBLOG-START.*?// LCBLOG-END\s*,?\n", re.S | re.M)
    cleaned = pattern.sub("", src)

    # Find dsa block, then locate the close of dsa.children specifically.
    m = re.search(r"^    name: 'dsa',\s*\n", cleaned, re.M)
    if not m:
        sys.exit("could not find dsa block in blog.js")
    after_start = m.end()
    rel = re.search(r"\n    \]\n  \},\n", cleaned[after_start:])
    if not rel:
        sys.exit("could not find dsa block close in blog.js")
    close_abs = after_start + rel.start() + 1  # +1 to land just after the leading \n

    block = build_tree_block(contests)
    tree_str = block + "\n"
    # Splice: ensure prev sibling has trailing comma, then insert our block.
    head = cleaned[:close_abs]
    tail = cleaned[close_abs:]
    # head ends with `      }\n` (or `}` followed by newline) for the last sibling.
    # Add a comma after that closing `}` if missing.
    head_fixed = re.sub(r"(\n      \})(\n)\Z", r"\1,\n", head)
    if head_fixed == head:
        # try alternative: maybe last sibling is at depth >6
        head_fixed = re.sub(r"(\n([ \t]+)\})(\n)\Z", r"\1,\n", head)
        if head_fixed == head:
            sys.exit("could not find last dsa.children sibling close to comma-fix")
    new_src = head_fixed + tree_str + tail
    if new_src == cleaned:
        sys.exit("splice no-op — pattern not matched")
    BLOG_JS.write_text(new_src, encoding="utf-8")
    print(f"blog.js: spliced LCBLOG block ({len(contests)} contests)")


# ---------- BLOG_POSTS block ----------

def build_posts_block(contests: list[dict]) -> str:
    out: list[str] = []
    out.append("  /* LCBLOG-START (auto-generated by tools/update_registries.py — do not edit by hand) */")
    # Series landing
    out.append(
        "  'dsa/leetcode-contests/index.html': { "
        "category: 'dsa', series: 'LeetCode Past Contests', "
        "title: 'LeetCode Past Contests', "
        "description: 'Editorial-style C++ writeups for every LeetCode Weekly and Biweekly contest.', "
        "meta: 'Series Index' },"
    )
    for c in sorted(contests, key=lambda x: (x["kind"], x["number"])):
        kind = c["kind"]
        n = c["number"]
        num3 = f"{n:03d}"
        human = f"{kind.capitalize()} Contest {n}"
        base = f"dsa/leetcode-contests/{kind}/{num3}"
        series = f"LeetCode Past Contests &middot; {kind.capitalize()} {n}"
        # Contest index
        out.append(
            f"  '{base}/index.html': {{ "
            f"category: 'dsa', series: {js_str_dq(series)}, "
            f"title: {js_str_dq(human)}, "
            f"description: {js_str_dq('Overview and editorial links for ' + human + '.')}, "
            f"meta: {js_str_dq(human + ' · Overview')} }},"
        )
        for p in c["problems"]:
            file = f"{base}/q{p['order']}-{p['slug']}.html"
            title = f"Q{p['order']}. {p['title']}"
            desc = f"{human}, Problem {p['order']}: {p['title']}. C++ editorial with intuition, brute force, optimal approach, dry run, complexity, and edge cases."
            meta = f"{human} · Q{p['order']}"
            out.append(
                f"  '{file}': {{ "
                f"category: 'dsa', series: {js_str_dq(series)}, "
                f"title: {js_str_dq(title)}, "
                f"description: {js_str_dq(desc)}, "
                f"meta: {js_str_dq(meta)} }},"
            )
    out.append("  /* LCBLOG-END */")
    return "\n".join(out)


def js_str_dq(s: str) -> str:
    """Single-quoted JS string literal."""
    return "'" + s.replace("\\", "\\\\").replace("'", "\\'") + "'"


def splice_posts_js(contests: list[dict]) -> None:
    src = POSTS_JS.read_text(encoding="utf-8")
    pattern = re.compile(r"^  /\* LCBLOG-START.*?LCBLOG-END \*/\n", re.S | re.M)
    cleaned = pattern.sub("", src)

    # Insert before the final `};`.
    m = re.search(r"\n\};\s*\Z", cleaned)
    if not m:
        sys.exit("could not find closing `};` in blog-posts.js")
    block = build_posts_block(contests)
    new_src = cleaned[: m.start()] + "\n" + block + cleaned[m.start():]
    POSTS_JS.write_text(new_src, encoding="utf-8")
    n_entries = block.count("\n  '")
    print(f"blog-posts.js: spliced LCBLOG block ({n_entries} entries)")


# ---------- main ----------

def main() -> None:
    contests = json.loads(MANIFEST.read_text())
    splice_blog_js(contests)
    splice_posts_js(contests)


if __name__ == "__main__":
    main()
